title: Sagar Patel
description: Data Analyst
#site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Sagar-1496
#blog_url: https://www.nagekar.com
email: shaggy1868@gmail.com
#keybase_username: abhn
#twitter_username: abhn_
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 